exp_name: 'Trans_Lang_Model_1'
agent: 'TransLangModel'

cuda: true
seed: 1

some_model_attribute: 0
emsize: 512
d_hid : 1024
nlayers: 6
nhead: 8
dropout: 0.2
lr: 0.0003
epochs: 20
weight_decay: 0
beta1: 0.5
beta2: 0.999
momentum: 0.9
optimizer: 'sgd'

validate_every: 1000
log_interval: 1000

batch_size: 20
test_batch_size: 10

save_best: True

checkpoint_file: 'checkpoint.pth.tar'
checkpoint_dir: './experiments'

data_loader": 'WikiText2'
data_folder: 
  value: './data/WikiText2'
